# NYU CORE-UA 111 From Data to Discovery 
# public course materials
# intended to be used as a reference by the students

# Book properties
title: From Data to Discovery
author: Corrin Clarkson
#repository:
#  url: "https://github.com/nyumathclinic/core-ua_111_public"

# Build configuration
only_build_toc_files: true

## Buttons
html:
  use_repository_button: false
  
#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    - html_admonition # added, because GitHub does not support mark down admonitions.
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution

  myst_url_schemes          : [mailto, http, https]  # URI schemes that will be recognised as external URLs in Markdown links
